[workspace]
resolver = "3"
members = [
  "novadraw",
  "novadraw-math",
  "novadraw-geometry",
  "novadraw-core",
  "novadraw-render",
  "novadraw-scene",
  "novadraw-apps",

  "apps/editor",
  "apps/vello-app",
  "apps/shape-app",
  "apps/style-app",
  "apps/ndcanvas-app",
  "apps/transform-app",
  "apps/viewport-app",
  "apps/clip-app",
  "apps/layout-app",
  "apps/event-app",
  "apps/border-app",
  "apps/update-app",
  "apps/scroll-pane-demo",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
vello = "0.10.0"
glam = "0.30.9"
slotmap = "1.0.7"
uuid = { version = "1.18.1", features = ["v4", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
anyhow = "1.0.99"
winit = "0.30.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-appender = "0.2"
pollster = "0.4.0"
stacker = "0.1.25"
