[package]
name = "r8-perf"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
novadraw = { path = "../../novadraw", default-features = false }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
  "Win32_System_ProcessStatus",
  "Win32_System_Threading",
] }
