[package]
name = "border-app"
version.workspace = true
edition.workspace = true

[dependencies]
winit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
novadraw = { path = "../../../novadraw", features = ["native-vello"] }
novadraw-apps = { path = "../../support" }
novadraw-demo-scenes = { path = "../../scenes" }
pollster.workspace = true
