[package]
name = "native-vello-perf"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
novadraw = { path = "../../novadraw", default-features = false }
novadraw-backend-vello = { path = "../../novadraw-backend-vello", features = ["native"] }
serde.workspace = true
serde_json.workspace = true
winit.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-core-graphics = { version = "0.3.2", features = [
  "CGDataProvider",
  "CGEvent",
  "CGEventSource",
  "CGEventTypes",
  "CGGeometry",
  "CGImage",
  "CGRemoteOperation",
  "CGWindow",
  "libc",
] }
raw-window-handle.workspace = true
