[package]
name = "shape-app"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
winit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
novadraw = { path = "../../../novadraw" }
novadraw-example-support = { path = "../../support" }
novadraw-example-scenes = { path = "../../scenes" }
pollster.workspace = true
