[package]
name = "novadraw-render"
version.workspace = true
edition.workspace = true

[dependencies]
novadraw-geometry = { path = "../novadraw-geometry" }
novadraw-math = { path = "../novadraw-math" }
novadraw-core = { path = "../novadraw-core" }
glam.workspace = true
serde.workspace = true
tracing.workspace = true

vello = { workspace = true, optional = true }
winit = { workspace = true, optional = true }
pollster = { version = "0.4.0", optional = true }
image = { version = "0.25", default-features = false, features = ["png"], optional = true }

[features]
default = []
vello = ["dep:vello", "dep:winit", "dep:pollster", "dep:image"]
