[package]
name = "novadraw-render"
version.workspace = true
edition.workspace = true

[dependencies]
novadraw-geometry = { path = "../novadraw-geometry" }
novadraw-core = { path = "../novadraw-core" }
serde.workspace = true
tracing.workspace = true
uuid.workspace = true
parley.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
resvg.workspace = true
kurbo.workspace = true

[features]
default = []
