[package]
name = "novadraw"
version.workspace = true
edition.workspace = true
readme = "README.md"

[features]
default = []
debug_render = []

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
kurbo.workspace = true
parley.workspace = true
resvg.workspace = true
serde.workspace = true
slotmap.workspace = true
stacker.workspace = true
tracing.workspace = true
unicode-segmentation.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
