[package]
name = "novadraw-scene"
version.workspace = true
edition.workspace = true

[dependencies]
novadraw-geometry = { path = "../novadraw-geometry" }
novadraw-math = { path = "../novadraw-math" }
novadraw-core = { path = "../novadraw-core" }
novadraw-render = { path = "../novadraw-render", features = ["vello"] }
glam.workspace = true
slotmap.workspace = true
uuid.workspace = true
serde.workspace = true
tracing.workspace = true
stacker.workspace = true

[features]
default = []
debug_render = []
vello = ["novadraw-render/vello"]
