[package]
name = "node-editor-demo"
version.workspace = true
edition.workspace = true

[dependencies]
novadraw = { path = "../../../novadraw", features = ["native-vello"] }
novadraw-apps = { path = "../../support" }
pollster.workspace = true
serde.workspace = true
serde_json.workspace = true
winit.workspace = true
