[package]
name = "node-editor-demo"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
novadraw = { path = "../../../novadraw" }
novadraw-backend-vello = { path = "../../../novadraw-backend-vello", features = ["native"] }
novadraw-editor = { path = "../../../novadraw-editor" }
novadraw-platform-winit = { path = "../../../novadraw-platform-winit" }
novadraw-example-support = { path = "../../support" }
pollster.workspace = true
serde.workspace = true
serde_json.workspace = true
winit.workspace = true
