[package]
name = "web-validation"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
novadraw = { path = "../../novadraw", default-features = false }
novadraw-apps = { path = "../../novadraw-apps", default-features = false }
wasm-bindgen = "0.2.127"

[dependencies.web-sys]
version = "0.3.104"
features = [
  "CanvasRenderingContext2d",
  "CssStyleDeclaration",
  "Document",
  "DomRect",
  "Element",
  "Event",
  "EventTarget",
  "HtmlButtonElement",
  "HtmlCanvasElement",
  "HtmlElement",
  "KeyboardEvent",
  "PointerEvent",
  "WheelEvent",
  "Window",
]
