[package]
name = "ndcanvas-app"
default-run = "ndcanvas-app"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
winit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
novadraw = { path = "../../../novadraw" }
novadraw-example-support = { path = "../../support" }
novadraw-example-scenes = { path = "../../scenes" }
novadraw-backend-vello = { path = "../../../novadraw-backend-vello", features = ["native"] }
pollster.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
